
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CKDatabaseConnection.EF
{

using System;
    using System.Collections.Generic;
    
public partial class CasinoKiosk_ChangeLog
{

    public int ID { get; set; }

    public Nullable<int> ItemID { get; set; }

    public string OldName { get; set; }

    public string NewName { get; set; }

    public Nullable<int> OldPoints { get; set; }

    public Nullable<int> NewPoints { get; set; }

    public Nullable<int> OldQuantity { get; set; }

    public Nullable<int> NewQuantity { get; set; }

    public string OldImageURL { get; set; }

    public string NewImageUrl { get; set; }

    public Nullable<bool> OldIsActive { get; set; }

    public Nullable<bool> NewIsActive { get; set; }

    public Nullable<System.DateTime> ChangedDate { get; set; }

    public string ChangedPerson { get; set; }

}

}
