
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CKDatabaseConnection.EF
{

using System;
    using System.Collections.Generic;
    
public partial class CasinoTrackingActivity
{

    public int ID { get; set; }

    public string UserName { get; set; }

    public Nullable<int> GuestPID { get; set; }

    public string GuestName { get; set; }

    public string CallRecord { get; set; }

    public string ChatRecord { get; set; }

    public string MeetRecord { get; set; }

    public string Type { get; set; }

    public string CreatedDate { get; set; }

    public Nullable<bool> isShow { get; set; }

}

}
