
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CKDatabaseConnection.EF
{

using System;
    using System.Collections.Generic;
    
public partial class CurrencyConverter_User
{

    public int ID { get; set; }

    public string UserName { get; set; }

    public string Role { get; set; }

    public Nullable<System.DateTime> CreatedTime { get; set; }

    public Nullable<bool> isActive { get; set; }

    public Nullable<System.DateTime> LastLogin { get; set; }

    public string Password { get; set; }

    public Nullable<bool> isShow { get; set; }

}

}
