
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CKDatabaseConnection.EF
{

using System;
    using System.Collections.Generic;
    
public partial class HTRPromotionPlayerModifyLog
{

    public int Id { get; set; }

    public int PromotionID { get; set; }

    public int PlayerID { get; set; }

    public string OldPlayerName { get; set; }

    public string NewPlayerName { get; set; }

    public string UpdatedBy { get; set; }

    public System.DateTime UpdatedTime { get; set; }

}

}
