//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKDatabaseConnection.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFBonus_ReprintLog
    {
        public int ID { get; set; }
        public int TicketNo { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PromotionName { get; set; }
        public string ItemName { get; set; }
        public string PrintedBy { get; set; }
        public string PrintedDate { get; set; }
    }
}
