//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKDatabaseConnection.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RA_SecurityEntities : DbContext
    {
        public RA_SecurityEntities()
            : base("name=RA_SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FCardIDRefPID> FCardIDRefPIDs { get; set; }
    
        public virtual ObjectResult<sp_GetCasinoDoorLog_Result> sp_GetCasinoDoorLog(string begin_Date)
        {
            var begin_DateParameter = begin_Date != null ?
                new ObjectParameter("begin_Date", begin_Date) :
                new ObjectParameter("begin_Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCasinoDoorLog_Result>("sp_GetCasinoDoorLog", begin_DateParameter);
        }
    }
}
