//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKDatabaseConnection.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WheelOfFortuneEntities : DbContext
    {
        public WheelOfFortuneEntities()
            : base("name=WheelOfFortuneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WoF_Prize> WoF_Prize { get; set; }
        public virtual DbSet<WoF_Prize_Log> WoF_Prize_Log { get; set; }
    
        public virtual ObjectResult<WoF_GetWheelOfFortuneLog_Result> WoF_GetWheelOfFortuneLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WoF_GetWheelOfFortuneLog_Result>("WoF_GetWheelOfFortuneLog");
        }
    }
}
